services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony_user -d symfony_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
